project:
  type: website

website:
  title: "Sunny Tseng 曾奕晴"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: academic.qmd
        text: Academic
      - href: science.qmd
        text: Science
      - href: art.qmd
        text: Art
      - href: blog.qmd
        text: Blog
      - href: sound.qmd
        text: Sound

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

