project:
  type: website

website:
  title: "曾奕晴 Sunny Tseng"
  back-to-top-navigation: true
  navbar:
    search: true
    background: light
    foreground: secondary
    right:
      - href: index.qmd
        text: Home
        
      - href: about.qmd
        text: About
        
      - text: Science
        menu: 
        - href: science/writing.qmd
          text: Popular Science Writing
        - href: science/project.qmd
          text: Research Project
        - href: science/academic.qmd
          text: Academic CV

      - text: Art
        menu:
        - href: art/design.qmd
          text: Infographic Design
        - href: art/fine_art.qmd
          text: Fine Art
          
      - href: blog.qmd
        text: Blog
        
      - href: sound.qmd
        text: Sound
  
        
  page-navigation: true
  
  page-footer: 
    right: "Created with Quarto by Sunny Tseng. Updated 2026 Sep."

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    
editor: source

lightbox: true

execute:
  freeze: auto
