project:
  type: website

website:
  title: "Sunny Tseng 曾奕晴"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: Science
        menu: 
        - href: science/academic.qmd
          text: Academic CV
        - href: science/project.qmd
          text: Research Project
        - href: science/writing.qmd
          text: Popular Science Writing
      - href: art.qmd
        text: Art
      - href: blog.qmd
        text: Blog
      - href: sound.qmd
        text: Sound

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

